favicon: https://cdn.jsdelivr.net/gh/61hhh/imageLake@main/iconMe.svg
banner: https://cdn.jsdelivr.net/gh/61hhh/imageLake@main/lightBG.jpg

logo:
  expanded: https://cdn.jsdelivr.net/gh/61hhh/imageLake@main/sidebar3_1.png
  collapsed: https://cdn.jsdelivr.net/gh/61hhh/imageLake@main/iconMe.png
  dark: https://npm.elemecdn.com/hassan-assets/navi/logo_dark@2x.png

flag:
  icon: flag-cn
  name: China

search: true


menu:
  - name: 折腾
    icon: iconfont icon-code
    submenu:
      - name: 博览群书
        icon: iconfont icon-blog
        config: 博览群书
      - name: 云游四海
        icon: iconfont icon-social
        config: 云游四海


# about:
#   url: /about/
#   icon: far fa-heart
#   name: 关于本站

# aboutPage:
#   website:
#     head: 关于本站
#     html: '<blockquote><p>本站是由<a href="https://github.com/hassanblog">Hassan Wong</a>基于<a href="https://hexo.io/">Hexo框架</a>主题为<a href="https://github.com/HCLonely/hexo-theme-webstack">WebStack</a>所搭建的。</p></blockquote>'
#   webmaster:
#     head: 关于站长
#     name: Hassan Wong
#     url: https://hassanwong.top
#     img: https://npm.elemecdn.com/hassan-assets/navi/logos/myblog.png
#     description: 时不我待，只争朝夕
#     html: ""

since: 2022

busuanzi:
  enable: true
  position: footer # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <link rel="stylesheet" type="text/css" href="/css/custom.css">
    <link rel="stylesheet" type="text/css" href="//at.alicdn.com/t/font_2204525_jxth1d6fs6o.css">
    <link rel="stylesheet" href="//s1.hdslb.com/bfs/static/jinkela/long/font/regular.css" media="all" onload="this.media='all'" />
  body: # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <div class="bg"></div>
    <script src="/js/custom.js"></script>
    <script src="/js/lozad.min.js"></script>
js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
